### ISSUE TITLE
Fizeau

### ISSUE THREAD

**Issue by ZweiBR** [JuniorPassos/Arquivos-JNX#1]
Olá meu amigo
Gostaria de saber por que o Fizeau removido ele apresenta algum erro no switch ?

**Comment by JuniorPassos** [comment]
> Olá meu amigo
> Gostaria de saber por que o Fizeau removido ele apresenta algum erro no switch ?

Não fiz os testes dele na FW17.0.0 pois não o uso mais. 
Por isso removi do meu pack já que não farei novas traduções em cima dos arquivos originais.
Caso queira testar, é só acessar a página do dev do Fizeau.
