### ISSUE TITLE
GBA Pack

### ISSUE THREAD

**Issue by marmundo** [JuniorPassos/Arquivos-JNX#2]
Junior eu não sei se foi você que criou o pack de gba que está no cnx. Se foi poderia atualizar o pack para a versão mais nova do gba online (v1.4). Obrigado

**Comment by JuniorPassos** [comment]
> Junior eu não sei se foi você que criou o pack de gba que está no cnx. Se foi poderia atualizar o pack para a versão mais nova do gba online (v1.4). Obrigado

Sim, foi eu quem criou o pack do GBA que está no CNX Updater porém o pack não precisa de atualização.
Testei aqui e está funcionando normalmente na versão 1.4.0  atual.

**Comment by marmundo** [comment]
Estranho. Eu estava com a versão 1.4 e fiz o download do seu pack e ele não
reconheceu. De qualquer forma eu consegui apenas com a versão base do gba.

Muito obrigado pelo trabalho feito e pelo feedback.

Marcelo Damasceno
